import { readdirSync, writeFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const ASSETS = join(ROOT, 'assets')

const CATEGORY = {
  人物模型: 'people',
  城墙和大门和防御设施素材: 'fort',
  室内装饰模型: 'interior',
  枪械包: 'guns',
  生存素材模型: 'survival',
  自然模型包: 'natureClump',
  自然模型包大多: 'nature',
  食物素材模型: 'food',
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('._') || entry.name === '.DS_Store') continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) walk(full, out)
    else if (entry.name.toLowerCase().endsWith('.glb')) out.push(full)
  }
  return out
}

function normalizeName(fileName) {
  return fileName
    .replace(/\.glb$/i, '')
    .replace(/\s+by Quaternius\s+-\s+[A-Za-z0-9]+$/i, '')
    .replace(/-[A-Za-z0-9]{8,}$/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function slug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const files = walk(ASSETS).sort()
const used = new Map()
const entries = []

for (const full of files) {
  const rel = relative(ASSETS, full).replaceAll('\\', '/')
  const folder = rel.split('/')[0]
  const category = CATEGORY[folder] ?? (rel === folder ? 'people' : null)
  if (!category) continue
  const name = normalizeName(rel.split('/').pop() ?? rel)
  const base = `${category}/${slug(name) || 'asset'}`
  const count = (used.get(base) ?? 0) + 1
  used.set(base, count)
  const id = count === 1 ? base : `${base}-${count}`
  entries.push({
    id,
    name,
    category,
    file: rel,
    bytes: statSync(full).size,
  })
}

const body = `/* Generated by scripts/index-assets.mjs — do not edit by hand. */
export type AssetCategory =
  | 'people'
  | 'fort'
  | 'interior'
  | 'guns'
  | 'survival'
  | 'natureClump'
  | 'nature'
  | 'food'

export interface AssetEntry {
  id: string
  name: string
  category: AssetCategory
  file: string
  bytes: number
}

export const ASSET_INDEX: readonly AssetEntry[] = ${JSON.stringify(entries, null, 2)}

export function assetById(id: string): AssetEntry | undefined {
  return ASSET_INDEX.find((entry) => entry.id === id)
}

export function assetsIn(category: AssetCategory): AssetEntry[] {
  return ASSET_INDEX.filter((entry) => entry.category === category)
}

export function assetUrl(file: string): string {
  return \`/assets/\${file.split('/').map(encodeURIComponent).join('/')}\`
}
`

writeFileSync(join(ROOT, 'src/data/assetIndex.ts'), body)
console.log(`indexed ${entries.length} glbs`)
