/* Generated by scripts/index-assets.mjs — do not edit by hand. */
export type AssetCategory =
  | 'people'
  | 'fort'
  | 'interior'
  | 'guns'
  | 'survival'
  | 'natureClump'
  | 'nature'
  | 'food'

export interface AssetEntry {
  id: string
  name: string
  category: AssetCategory
  file: string
  bytes: number
}

export const ASSET_INDEX: readonly AssetEntry[] = [
  {
    "id": "people/adventurer",
    "name": "Adventurer",
    "category": "people",
    "file": "人物模型/Adventurer by Quaternius - 5EGWBMpuXq.glb",
    "bytes": 1944116
  },
  {
    "id": "people/animated-woman",
    "name": "Animated Woman",
    "category": "people",
    "file": "人物模型/Animated Woman by Quaternius - nIItLV9nxS.glb",
    "bytes": 1491780
  },
  {
    "id": "people/beach-character",
    "name": "Beach Character",
    "category": "people",
    "file": "人物模型/Beach Character by Quaternius - DojKLcO34E.glb",
    "bytes": 1505104
  },
  {
    "id": "people/business-man",
    "name": "Business Man",
    "category": "people",
    "file": "人物模型/Business Man by Quaternius - JFrLIKqvCH.glb",
    "bytes": 1529248
  },
  {
    "id": "people/hoodie-character",
    "name": "Hoodie Character",
    "category": "people",
    "file": "人物模型/Hoodie Character by Quaternius - gKLBoRsyKe.glb",
    "bytes": 1456760
  },
  {
    "id": "people/man",
    "name": "Man",
    "category": "people",
    "file": "人物模型/Man by Quaternius - HMnuH5geEG.glb",
    "bytes": 493196
  },
  {
    "id": "people/punk",
    "name": "Punk",
    "category": "people",
    "file": "人物模型/Punk by Quaternius - BTALZymknF.glb",
    "bytes": 1374172
  },
  {
    "id": "people/punk-2",
    "name": "Punk",
    "category": "people",
    "file": "人物模型/Punk by Quaternius - djXoqejw6w.glb",
    "bytes": 1474996
  },
  {
    "id": "people/swat",
    "name": "SWAT",
    "category": "people",
    "file": "人物模型/SWAT by Quaternius - Btfn3G5Xv4.glb",
    "bytes": 1560900
  },
  {
    "id": "people/soldier",
    "name": "Soldier",
    "category": "people",
    "file": "人物模型/Soldier by Quaternius - oAArCNHjFB.glb",
    "bytes": 1703996
  },
  {
    "id": "people/worker",
    "name": "Worker",
    "category": "people",
    "file": "人物模型/Worker by Quaternius - Yg2bQZO6Hj.glb",
    "bytes": 1344928
  },
  {
    "id": "fort/archery-building",
    "name": "Archery Building",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Building.glb",
    "bytes": 442584
  },
  {
    "id": "fort/archery-second-age-le",
    "name": "Archery Second Age Le",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Second Age Le.glb",
    "bytes": 381300
  },
  {
    "id": "fort/archery-towers",
    "name": "Archery Towers",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Towers-IA5qOjIAiT.glb",
    "bytes": 625020
  },
  {
    "id": "fort/archery-towers-2",
    "name": "Archery Towers",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Towers.glb",
    "bytes": 399808
  },
  {
    "id": "fort/archery-training-grounds",
    "name": "Archery Training Grounds",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Training Grounds-5dWpau7C3k.glb",
    "bytes": 320668
  },
  {
    "id": "fort/archery-training-grounds-2",
    "name": "Archery Training Grounds",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Archery Training Grounds.glb",
    "bytes": 251348
  },
  {
    "id": "fort/barracks",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks-UXCOwRBSxx.glb",
    "bytes": 583772
  },
  {
    "id": "fort/barracks-2",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks-a1C1L8gJTX.glb",
    "bytes": 137960
  },
  {
    "id": "fort/barracks-3",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks-dvlksXgxWc.glb",
    "bytes": 486740
  },
  {
    "id": "fort/barracks-4",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks-lnyADheSvA.glb",
    "bytes": 226912
  },
  {
    "id": "fort/barracks-5",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks-puD1kbV4kf.glb",
    "bytes": 273848
  },
  {
    "id": "fort/barracks-6",
    "name": "Barracks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Barracks.glb",
    "bytes": 79112
  },
  {
    "id": "fort/business-building",
    "name": "Business Building",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Business Building.glb",
    "bytes": 529520
  },
  {
    "id": "fort/castle-fortress",
    "name": "Castle Fortress",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Castle Fortress.glb",
    "bytes": 593072
  },
  {
    "id": "fort/castle-gate",
    "name": "Castle Gate",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Castle Gate.glb",
    "bytes": 147652
  },
  {
    "id": "fort/castle",
    "name": "Castle",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Castle-y15yE6kWLY.glb",
    "bytes": 544976
  },
  {
    "id": "fort/castle-2",
    "name": "Castle",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Castle.glb",
    "bytes": 477160
  },
  {
    "id": "fort/crops",
    "name": "Crops",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Crops.glb",
    "bytes": 1976880
  },
  {
    "id": "fort/dock",
    "name": "Dock",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Dock-XViKoBh2UN.glb",
    "bytes": 18520
  },
  {
    "id": "fort/dock-2",
    "name": "Dock",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Dock.glb",
    "bytes": 17416
  },
  {
    "id": "fort/docks",
    "name": "Docks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Docks.glb",
    "bytes": 472544
  },
  {
    "id": "fort/farm-dirt",
    "name": "Farm Dirt",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Farm Dirt.glb",
    "bytes": 17916
  },
  {
    "id": "fort/farm",
    "name": "Farm",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Farm-91wMLb9kKo.glb",
    "bytes": 230864
  },
  {
    "id": "fort/farm-2",
    "name": "Farm",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Farm-O4wpTLSfIn.glb",
    "bytes": 124140
  },
  {
    "id": "fort/farm-3",
    "name": "Farm",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Farm.glb",
    "bytes": 143208
  },
  {
    "id": "fort/fortress",
    "name": "Fortress",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Fortress.glb",
    "bytes": 42912
  },
  {
    "id": "fort/gold-rocks",
    "name": "Gold Rocks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Gold Rocks.glb",
    "bytes": 44780
  },
  {
    "id": "fort/house",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-RSwoYSLblu.glb",
    "bytes": 157096
  },
  {
    "id": "fort/house-2",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-YlADpCJU8U.glb",
    "bytes": 49332
  },
  {
    "id": "fort/house-3",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-k6tP5nFUd2.glb",
    "bytes": 180832
  },
  {
    "id": "fort/house-4",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-nihGGju7DW.glb",
    "bytes": 76900
  },
  {
    "id": "fort/house-5",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-oJJIRwv6Bo.glb",
    "bytes": 108228
  },
  {
    "id": "fort/house-6",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House-vZ1CLbWmSx.glb",
    "bytes": 152984
  },
  {
    "id": "fort/house-7",
    "name": "House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/House.glb",
    "bytes": 57660
  },
  {
    "id": "fort/houses",
    "name": "Houses",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Houses-gEjAC1UvVU.glb",
    "bytes": 262976
  },
  {
    "id": "fort/houses-2",
    "name": "Houses",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Houses-vCoDG5hFyI.glb",
    "bytes": 163984
  },
  {
    "id": "fort/houses-3",
    "name": "Houses",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Houses.glb",
    "bytes": 113188
  },
  {
    "id": "fort/hut",
    "name": "Hut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Hut-4MJWbyd6vw.glb",
    "bytes": 36276
  },
  {
    "id": "fort/hut-2",
    "name": "Hut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Hut-wxi3kAu5ey.glb",
    "bytes": 95376
  },
  {
    "id": "fort/hut-3",
    "name": "Hut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Hut.glb",
    "bytes": 24012
  },
  {
    "id": "fort/huts",
    "name": "Huts",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Huts.glb",
    "bytes": 92724
  },
  {
    "id": "fort/logs",
    "name": "Logs",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Logs.glb",
    "bytes": 27728
  },
  {
    "id": "fort/market-stalls-compact",
    "name": "Market Stalls Compact",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Market Stalls Compact.glb",
    "bytes": 987996
  },
  {
    "id": "fort/market-stalls",
    "name": "Market Stalls",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Market Stalls-4ZAhRv2tLG.glb",
    "bytes": 344572
  },
  {
    "id": "fort/market-stalls-2",
    "name": "Market Stalls",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Market Stalls-OLd8vu6lPL.glb",
    "bytes": 585880
  },
  {
    "id": "fort/market-stalls-3",
    "name": "Market Stalls",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Market Stalls-PUZZ5F91OE.glb",
    "bytes": 249412
  },
  {
    "id": "fort/market-stalls-4",
    "name": "Market Stalls",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Market Stalls.glb",
    "bytes": 142592
  },
  {
    "id": "fort/mine",
    "name": "Mine",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Mine.glb",
    "bytes": 141868
  },
  {
    "id": "fort/mountain-group",
    "name": "Mountain Group",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Mountain Group.glb",
    "bytes": 58428
  },
  {
    "id": "fort/mountain",
    "name": "Mountain",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Mountain-XY4ej3Zg3I.glb",
    "bytes": 47128
  },
  {
    "id": "fort/mountain-2",
    "name": "Mountain",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Mountain.glb",
    "bytes": 17360
  },
  {
    "id": "fort/mountains",
    "name": "Mountains",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Mountains.glb",
    "bytes": 154432
  },
  {
    "id": "fort/pine-trees",
    "name": "Pine Trees",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Pine Trees.glb",
    "bytes": 99604
  },
  {
    "id": "fort/port",
    "name": "Port",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Port-4sE6lmhGPF.glb",
    "bytes": 410920
  },
  {
    "id": "fort/port-2",
    "name": "Port",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Port.glb",
    "bytes": 299940
  },
  {
    "id": "fort/resource-gold",
    "name": "Resource Gold",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Resource Gold.glb",
    "bytes": 51048
  },
  {
    "id": "fort/rock",
    "name": "Rock",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Rock-JmFMh7ztL9.glb",
    "bytes": 28332
  },
  {
    "id": "fort/rock-2",
    "name": "Rock",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Rock-RtLRqYjfMs.glb",
    "bytes": 30648
  },
  {
    "id": "fort/rock-3",
    "name": "Rock",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Rock.glb",
    "bytes": 9116
  },
  {
    "id": "fort/rocks",
    "name": "Rocks",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Rocks.glb",
    "bytes": 21088
  },
  {
    "id": "fort/shack",
    "name": "Shack",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Shack-HuzLJcbUd2.glb",
    "bytes": 58580
  },
  {
    "id": "fort/shack-2",
    "name": "Shack",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Shack.glb",
    "bytes": 44508
  },
  {
    "id": "fort/shipping-port",
    "name": "Shipping Port",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Shipping Port-rDX8W8uqip.glb",
    "bytes": 218584
  },
  {
    "id": "fort/shipping-port-2",
    "name": "Shipping Port",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Shipping Port.glb",
    "bytes": 219296
  },
  {
    "id": "fort/small-farm",
    "name": "Small Farm",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Small Farm.glb",
    "bytes": 127588
  },
  {
    "id": "fort/small-watch-tower",
    "name": "Small Watch Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Small Watch Tower.glb",
    "bytes": 38744
  },
  {
    "id": "fort/stone-tower",
    "name": "Stone Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Stone Tower-dJLAD6p90F.glb",
    "bytes": 217660
  },
  {
    "id": "fort/stone-tower-2",
    "name": "Stone Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Stone Tower.glb",
    "bytes": 204912
  },
  {
    "id": "fort/stone-wall-towers",
    "name": "Stone Wall Towers",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Stone Wall Towers.glb",
    "bytes": 125480
  },
  {
    "id": "fort/stone-wall",
    "name": "Stone Wall",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Stone Wall.glb",
    "bytes": 17992
  },
  {
    "id": "fort/storage-house",
    "name": "Storage House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Storage House.glb",
    "bytes": 551388
  },
  {
    "id": "fort/storage-hut",
    "name": "Storage Hut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Storage Hut.glb",
    "bytes": 200212
  },
  {
    "id": "fort/storage-shed",
    "name": "Storage Shed",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Storage Shed.glb",
    "bytes": 256252
  },
  {
    "id": "fort/storage-shed-2",
    "name": "Storage shed",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Storage shed-fkTsDdpQAA.glb",
    "bytes": 514028
  },
  {
    "id": "fort/temple-first-age-leve",
    "name": "Temple First Age Leve",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Temple First Age Leve.glb",
    "bytes": 634232
  },
  {
    "id": "fort/temple",
    "name": "Temple",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Temple-CE2Mn7lh6A.glb",
    "bytes": 292004
  },
  {
    "id": "fort/temple-2",
    "name": "Temple",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Temple-nR264crTSr.glb",
    "bytes": 277956
  },
  {
    "id": "fort/temple-3",
    "name": "Temple",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Temple-v36uJiErXS.glb",
    "bytes": 125628
  },
  {
    "id": "fort/temple-4",
    "name": "Temple",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Temple.glb",
    "bytes": 26700
  },
  {
    "id": "fort/tower-house",
    "name": "Tower House",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Tower House.glb",
    "bytes": 230536
  },
  {
    "id": "fort/town-center-second-age",
    "name": "Town Center Second Age",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Town Center Second Age.glb",
    "bytes": 398512
  },
  {
    "id": "fort/town-center",
    "name": "Town Center",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Town Center-76GTkSh4KM.glb",
    "bytes": 240408
  },
  {
    "id": "fort/town-center-2",
    "name": "Town Center",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Town Center-CoERW5nFdE.glb",
    "bytes": 159508
  },
  {
    "id": "fort/town-center-3",
    "name": "Town Center",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Town Center-cuQuFJEIfH.glb",
    "bytes": 175228
  },
  {
    "id": "fort/town-center-4",
    "name": "Town Center",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Town Center.glb",
    "bytes": 49516
  },
  {
    "id": "fort/trees-cut",
    "name": "Trees cut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Trees cut-zhm3D5KKRh.glb",
    "bytes": 25196
  },
  {
    "id": "fort/trees-cut-2",
    "name": "Trees cut",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Trees cut.glb",
    "bytes": 31152
  },
  {
    "id": "fort/trees",
    "name": "Trees",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Trees.glb",
    "bytes": 92392
  },
  {
    "id": "fort/village-market",
    "name": "Village Market",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Village Market.glb",
    "bytes": 385312
  },
  {
    "id": "fort/wall-towers-door-seco",
    "name": "Wall Towers Door Seco",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wall Towers Door Seco.glb",
    "bytes": 133888
  },
  {
    "id": "fort/wall-towers",
    "name": "Wall Towers",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wall Towers.glb",
    "bytes": 83412
  },
  {
    "id": "fort/watch-tower",
    "name": "Watch Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Watch Tower-VJZZW37Vsk.glb",
    "bytes": 96872
  },
  {
    "id": "fort/watch-tower-2",
    "name": "Watch Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Watch Tower-cMxuj2gt7D.glb",
    "bytes": 189788
  },
  {
    "id": "fort/watch-tower-3",
    "name": "Watch Tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Watch Tower.glb",
    "bytes": 53188
  },
  {
    "id": "fort/windmill",
    "name": "Windmill",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Windmill-jpHoi9xDLG.glb",
    "bytes": 136688
  },
  {
    "id": "fort/windmill-2",
    "name": "Windmill",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Windmill.glb",
    "bytes": 126108
  },
  {
    "id": "fort/wodden-temple",
    "name": "Wodden Temple",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wodden Temple.glb",
    "bytes": 340820
  },
  {
    "id": "fort/wonder-first-age-leve",
    "name": "Wonder First Age Leve",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wonder First Age Leve.glb",
    "bytes": 633096
  },
  {
    "id": "fort/wooden-encampment",
    "name": "Wooden Encampment",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Encampment.glb",
    "bytes": 235640
  },
  {
    "id": "fort/wooden-fortress-gate",
    "name": "Wooden Fortress Gate",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Fortress Gate.glb",
    "bytes": 90984
  },
  {
    "id": "fort/wooden-fortress",
    "name": "Wooden Fortress",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Fortress.glb",
    "bytes": 476648
  },
  {
    "id": "fort/wooden-monument",
    "name": "Wooden Monument",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Monument.glb",
    "bytes": 245640
  },
  {
    "id": "fort/wooden-wall",
    "name": "Wooden Wall",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Wall-L0TxLurnES.glb",
    "bytes": 61744
  },
  {
    "id": "fort/wooden-wall-2",
    "name": "Wooden Wall",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden Wall.glb",
    "bytes": 18624
  },
  {
    "id": "fort/wooden-house-tower",
    "name": "Wooden house tower",
    "category": "fort",
    "file": "城墙和大门和防御设施素材/Wooden house tower.glb",
    "bytes": 119996
  },
  {
    "id": "interior/bathroom-sink",
    "name": "Bathroom Sink",
    "category": "interior",
    "file": "室内装饰模型/Bathroom Sink.glb",
    "bytes": 12708
  },
  {
    "id": "interior/bathroom-toilet-paper",
    "name": "Bathroom Toilet Paper",
    "category": "interior",
    "file": "室内装饰模型/Bathroom Toilet Paper.glb",
    "bytes": 13428
  },
  {
    "id": "interior/bathtub",
    "name": "Bathtub",
    "category": "interior",
    "file": "室内装饰模型/Bathtub.glb",
    "bytes": 10900
  },
  {
    "id": "interior/bed-king",
    "name": "Bed King",
    "category": "interior",
    "file": "室内装饰模型/Bed King.glb",
    "bytes": 25676
  },
  {
    "id": "interior/bed-single",
    "name": "Bed Single",
    "category": "interior",
    "file": "室内装饰模型/Bed Single.glb",
    "bytes": 23080
  },
  {
    "id": "interior/bunk-bed",
    "name": "Bunk Bed",
    "category": "interior",
    "file": "室内装饰模型/Bunk Bed.glb",
    "bytes": 31692
  },
  {
    "id": "interior/cactus",
    "name": "Cactus",
    "category": "interior",
    "file": "室内装饰模型/Cactus.glb",
    "bytes": 23044
  },
  {
    "id": "interior/ceiling-light",
    "name": "Ceiling Light",
    "category": "interior",
    "file": "室内装饰模型/Ceiling Light.glb",
    "bytes": 8840
  },
  {
    "id": "interior/chair",
    "name": "Chair",
    "category": "interior",
    "file": "室内装饰模型/Chair-Rlyhe93NNe.glb",
    "bytes": 13644
  },
  {
    "id": "interior/chair-2",
    "name": "Chair",
    "category": "interior",
    "file": "室内装饰模型/Chair.glb",
    "bytes": 13360
  },
  {
    "id": "interior/column-round",
    "name": "Column Round",
    "category": "interior",
    "file": "室内装饰模型/Column Round.glb",
    "bytes": 10748
  },
  {
    "id": "interior/couch-large",
    "name": "Couch Large",
    "category": "interior",
    "file": "室内装饰模型/Couch Large.glb",
    "bytes": 30800
  },
  {
    "id": "interior/couch-medium",
    "name": "Couch Medium",
    "category": "interior",
    "file": "室内装饰模型/Couch Medium-mWgQ94zhDZ.glb",
    "bytes": 22940
  },
  {
    "id": "interior/couch-medium-2",
    "name": "Couch Medium",
    "category": "interior",
    "file": "室内装饰模型/Couch Medium.glb",
    "bytes": 24232
  },
  {
    "id": "interior/couch-small",
    "name": "Couch Small",
    "category": "interior",
    "file": "室内装饰模型/Couch Small-X9msj0gtb5.glb",
    "bytes": 14940
  },
  {
    "id": "interior/couch-small-2",
    "name": "Couch Small",
    "category": "interior",
    "file": "室内装饰模型/Couch Small.glb",
    "bytes": 19048
  },
  {
    "id": "interior/curtains-double",
    "name": "Curtains Double",
    "category": "interior",
    "file": "室内装饰模型/Curtains Double.glb",
    "bytes": 13312
  },
  {
    "id": "interior/dead-houseplant",
    "name": "Dead Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Dead Houseplant.glb",
    "bytes": 19568
  },
  {
    "id": "interior/door-double",
    "name": "Door Double",
    "category": "interior",
    "file": "室内装饰模型/Door Double.glb",
    "bytes": 63624
  },
  {
    "id": "interior/door",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-8it1hH1oRu.glb",
    "bytes": 43820
  },
  {
    "id": "interior/door-2",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-KGt4ztcKrM.glb",
    "bytes": 11228
  },
  {
    "id": "interior/door-3",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-LI93WgnjyS.glb",
    "bytes": 24320
  },
  {
    "id": "interior/door-4",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-atrxVW0q9N.glb",
    "bytes": 42852
  },
  {
    "id": "interior/door-5",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-b0AIfzp6VL.glb",
    "bytes": 67044
  },
  {
    "id": "interior/door-6",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-ihXwSN12P1.glb",
    "bytes": 30724
  },
  {
    "id": "interior/door-7",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door-xuFNaNLzfE.glb",
    "bytes": 61568
  },
  {
    "id": "interior/door-8",
    "name": "Door",
    "category": "interior",
    "file": "室内装饰模型/Door.glb",
    "bytes": 41636
  },
  {
    "id": "interior/drawer",
    "name": "Drawer",
    "category": "interior",
    "file": "室内装饰模型/Drawer-8xZQEZL2w3.glb",
    "bytes": 17896
  },
  {
    "id": "interior/drawer-2",
    "name": "Drawer",
    "category": "interior",
    "file": "室内装饰模型/Drawer-G1H0wnCHQf.glb",
    "bytes": 15996
  },
  {
    "id": "interior/drawer-3",
    "name": "Drawer",
    "category": "interior",
    "file": "室内装饰模型/Drawer-N3ERi89OeO.glb",
    "bytes": 20612
  },
  {
    "id": "interior/drawer-4",
    "name": "Drawer",
    "category": "interior",
    "file": "室内装饰模型/Drawer-T4uDbyP90C.glb",
    "bytes": 33912
  },
  {
    "id": "interior/drawer-5",
    "name": "Drawer",
    "category": "interior",
    "file": "室内装饰模型/Drawer.glb",
    "bytes": 14944
  },
  {
    "id": "interior/fireplace",
    "name": "Fireplace",
    "category": "interior",
    "file": "室内装饰模型/Fireplace.glb",
    "bytes": 17728
  },
  {
    "id": "interior/houseplant",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant-IBLX2Jz90O.glb",
    "bytes": 20796
  },
  {
    "id": "interior/houseplant-2",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant-VtJh4Irl4w.glb",
    "bytes": 14412
  },
  {
    "id": "interior/houseplant-3",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant-bfLOqIV5uP.glb",
    "bytes": 16636
  },
  {
    "id": "interior/houseplant-4",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant-dveIJ0xNpX.glb",
    "bytes": 25884
  },
  {
    "id": "interior/houseplant-5",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant-f6GPjbEgg0.glb",
    "bytes": 10696
  },
  {
    "id": "interior/houseplant-6",
    "name": "Houseplant",
    "category": "interior",
    "file": "室内装饰模型/Houseplant.glb",
    "bytes": 17960
  },
  {
    "id": "interior/kitchen-fridge",
    "name": "Kitchen Fridge",
    "category": "interior",
    "file": "室内装饰模型/Kitchen Fridge.glb",
    "bytes": 17360
  },
  {
    "id": "interior/kitchen-sink",
    "name": "Kitchen Sink",
    "category": "interior",
    "file": "室内装饰模型/Kitchen Sink.glb",
    "bytes": 27220
  },
  {
    "id": "interior/l-couch",
    "name": "L Couch",
    "category": "interior",
    "file": "室内装饰模型/L Couch.glb",
    "bytes": 30700
  },
  {
    "id": "interior/lamp",
    "name": "Lamp",
    "category": "interior",
    "file": "室内装饰模型/Lamp.glb",
    "bytes": 10136
  },
  {
    "id": "interior/light-ceiling-single",
    "name": "Light Ceiling Single",
    "category": "interior",
    "file": "室内装饰模型/Light Ceiling Single.glb",
    "bytes": 10360
  },
  {
    "id": "interior/light-ceiling",
    "name": "Light Ceiling",
    "category": "interior",
    "file": "室内装饰模型/Light Ceiling-NNlnaiDJIh.glb",
    "bytes": 26540
  },
  {
    "id": "interior/light-ceiling-2",
    "name": "Light Ceiling",
    "category": "interior",
    "file": "室内装饰模型/Light Ceiling-ToOLJDO5FI.glb",
    "bytes": 26564
  },
  {
    "id": "interior/light-ceiling-3",
    "name": "Light Ceiling",
    "category": "interior",
    "file": "室内装饰模型/Light Ceiling.glb",
    "bytes": 10312
  },
  {
    "id": "interior/light-chandelier",
    "name": "Light Chandelier",
    "category": "interior",
    "file": "室内装饰模型/Light Chandelier.glb",
    "bytes": 25380
  },
  {
    "id": "interior/light-cube",
    "name": "Light Cube",
    "category": "interior",
    "file": "室内装饰模型/Light Cube-gJpALEpLcy.glb",
    "bytes": 24384
  },
  {
    "id": "interior/light-cube-2",
    "name": "Light Cube",
    "category": "interior",
    "file": "室内装饰模型/Light Cube.glb",
    "bytes": 23532
  },
  {
    "id": "interior/light-desk",
    "name": "Light Desk",
    "category": "interior",
    "file": "室内装饰模型/Light Desk.glb",
    "bytes": 12832
  },
  {
    "id": "interior/light-floor",
    "name": "Light Floor",
    "category": "interior",
    "file": "室内装饰模型/Light Floor-eBQtooeh43.glb",
    "bytes": 10112
  },
  {
    "id": "interior/light-floor-2",
    "name": "Light Floor",
    "category": "interior",
    "file": "室内装饰模型/Light Floor.glb",
    "bytes": 9964
  },
  {
    "id": "interior/light-icosahedron",
    "name": "Light Icosahedron",
    "category": "interior",
    "file": "室内装饰模型/Light Icosahedron.glb",
    "bytes": 61884
  },
  {
    "id": "interior/light-stand",
    "name": "Light Stand",
    "category": "interior",
    "file": "室内装饰模型/Light Stand.glb",
    "bytes": 10920
  },
  {
    "id": "interior/night-stand",
    "name": "Night Stand",
    "category": "interior",
    "file": "室内装饰模型/Night Stand-08S1j15Jcx.glb",
    "bytes": 10500
  },
  {
    "id": "interior/night-stand-2",
    "name": "Night Stand",
    "category": "interior",
    "file": "室内装饰模型/Night Stand-7cobkfclNv.glb",
    "bytes": 14364
  },
  {
    "id": "interior/night-stand-3",
    "name": "Night Stand",
    "category": "interior",
    "file": "室内装饰模型/Night Stand.glb",
    "bytes": 11148
  },
  {
    "id": "interior/oven",
    "name": "Oven",
    "category": "interior",
    "file": "室内装饰模型/Oven.glb",
    "bytes": 22896
  },
  {
    "id": "interior/round-rug",
    "name": "Round Rug",
    "category": "interior",
    "file": "室内装饰模型/Round Rug.glb",
    "bytes": 6628
  },
  {
    "id": "interior/rug",
    "name": "Rug",
    "category": "interior",
    "file": "室内装饰模型/Rug.glb",
    "bytes": 6020
  },
  {
    "id": "interior/shelf-large",
    "name": "Shelf Large",
    "category": "interior",
    "file": "室内装饰模型/Shelf Large.glb",
    "bytes": 13436
  },
  {
    "id": "interior/shelf-small",
    "name": "Shelf Small",
    "category": "interior",
    "file": "室内装饰模型/Shelf Small-TfdgUV2RYe.glb",
    "bytes": 6668
  },
  {
    "id": "interior/shelf-small-2",
    "name": "Shelf Small",
    "category": "interior",
    "file": "室内装饰模型/Shelf Small.glb",
    "bytes": 8828
  },
  {
    "id": "interior/square-plate",
    "name": "Square Plate",
    "category": "interior",
    "file": "室内装饰模型/Square Plate.glb",
    "bytes": 6376
  },
  {
    "id": "interior/stool",
    "name": "Stool",
    "category": "interior",
    "file": "室内装饰模型/Stool.glb",
    "bytes": 18068
  },
  {
    "id": "interior/table-lamp",
    "name": "Table Lamp",
    "category": "interior",
    "file": "室内装饰模型/Table Lamp.glb",
    "bytes": 10152
  },
  {
    "id": "interior/table-round-large",
    "name": "Table Round Large",
    "category": "interior",
    "file": "室内装饰模型/Table Round Large.glb",
    "bytes": 23024
  },
  {
    "id": "interior/table-round-small",
    "name": "Table Round Small",
    "category": "interior",
    "file": "室内装饰模型/Table Round Small-57W671WvS2.glb",
    "bytes": 18704
  },
  {
    "id": "interior/table-round-small-2",
    "name": "Table Round Small",
    "category": "interior",
    "file": "室内装饰模型/Table Round Small.glb",
    "bytes": 25236
  },
  {
    "id": "interior/toilet-paper-stack",
    "name": "Toilet Paper stack",
    "category": "interior",
    "file": "室内装饰模型/Toilet Paper stack.glb",
    "bytes": 14292
  },
  {
    "id": "interior/toilet",
    "name": "Toilet",
    "category": "interior",
    "file": "室内装饰模型/Toilet.glb",
    "bytes": 14344
  },
  {
    "id": "interior/towel-rack",
    "name": "Towel Rack",
    "category": "interior",
    "file": "室内装饰模型/Towel Rack.glb",
    "bytes": 11568
  },
  {
    "id": "interior/trashcan-large",
    "name": "Trashcan Large",
    "category": "interior",
    "file": "室内装饰模型/Trashcan Large.glb",
    "bytes": 21140
  },
  {
    "id": "interior/trashcan-small",
    "name": "Trashcan Small",
    "category": "interior",
    "file": "室内装饰模型/Trashcan Small-ZWYTK2SmBA.glb",
    "bytes": 13856
  },
  {
    "id": "interior/trashcan-small-2",
    "name": "Trashcan Small",
    "category": "interior",
    "file": "室内装饰模型/Trashcan Small.glb",
    "bytes": 11796
  },
  {
    "id": "interior/trashcan",
    "name": "Trashcan",
    "category": "interior",
    "file": "室内装饰模型/Trashcan-XSwahu252t.glb",
    "bytes": 24452
  },
  {
    "id": "interior/trashcan-2",
    "name": "Trashcan",
    "category": "interior",
    "file": "室内装饰模型/Trashcan.glb",
    "bytes": 12636
  },
  {
    "id": "interior/washing-machine",
    "name": "Washing Machine",
    "category": "interior",
    "file": "室内装饰模型/Washing Machine.glb",
    "bytes": 16584
  },
  {
    "id": "interior/window-large",
    "name": "Window Large",
    "category": "interior",
    "file": "室内装饰模型/Window Large.glb",
    "bytes": 20180
  },
  {
    "id": "interior/window-round",
    "name": "Window Round",
    "category": "interior",
    "file": "室内装饰模型/Window Round.glb",
    "bytes": 8528
  },
  {
    "id": "interior/window-small",
    "name": "Window Small",
    "category": "interior",
    "file": "室内装饰模型/Window Small.glb",
    "bytes": 8992
  },
  {
    "id": "guns/assault-rifle-ammo-box",
    "name": "Assault Rifle Ammo Box",
    "category": "guns",
    "file": "枪械包/Assault Rifle Ammo Box.glb",
    "bytes": 53556
  },
  {
    "id": "guns/assault-rifle",
    "name": "Assault Rifle",
    "category": "guns",
    "file": "枪械包/Assault Rifle-MdbcTe6hH3.glb",
    "bytes": 91936
  },
  {
    "id": "guns/assault-rifle-2",
    "name": "Assault Rifle",
    "category": "guns",
    "file": "枪械包/Assault Rifle-XGeBGFQxYg.glb",
    "bytes": 73044
  },
  {
    "id": "guns/assault-rifle-3",
    "name": "Assault Rifle",
    "category": "guns",
    "file": "枪械包/Assault Rifle.glb",
    "bytes": 74864
  },
  {
    "id": "guns/pistol-ammo",
    "name": "Pistol Ammo",
    "category": "guns",
    "file": "枪械包/Pistol Ammo.glb",
    "bytes": 48048
  },
  {
    "id": "guns/pistol",
    "name": "Pistol",
    "category": "guns",
    "file": "枪械包/Pistol-L1u7KkJzY2.glb",
    "bytes": 74788
  },
  {
    "id": "guns/pistol-2",
    "name": "Pistol",
    "category": "guns",
    "file": "枪械包/Pistol-M6RRKnpfim.glb",
    "bytes": 93932
  },
  {
    "id": "guns/pistol-3",
    "name": "Pistol",
    "category": "guns",
    "file": "枪械包/Pistol.glb",
    "bytes": 37504
  },
  {
    "id": "guns/revolver",
    "name": "Revolver",
    "category": "guns",
    "file": "枪械包/Revolver-E9wrywgP9D.glb",
    "bytes": 62536
  },
  {
    "id": "guns/revolver-2",
    "name": "Revolver",
    "category": "guns",
    "file": "枪械包/Revolver.glb",
    "bytes": 51220
  },
  {
    "id": "guns/shotgun-ammo",
    "name": "Shotgun Ammo",
    "category": "guns",
    "file": "枪械包/Shotgun Ammo.glb",
    "bytes": 32316
  },
  {
    "id": "guns/shotgun",
    "name": "Shotgun",
    "category": "guns",
    "file": "枪械包/Shotgun-f54ZSBZZ8k.glb",
    "bytes": 52248
  },
  {
    "id": "guns/shotgun-2",
    "name": "Shotgun",
    "category": "guns",
    "file": "枪械包/Shotgun.glb",
    "bytes": 32828
  },
  {
    "id": "guns/smg-ammo-box",
    "name": "Smg Ammo Box",
    "category": "guns",
    "file": "枪械包/Smg Ammo Box.glb",
    "bytes": 153420
  },
  {
    "id": "guns/sniper-ammo-box",
    "name": "Sniper Ammo Box",
    "category": "guns",
    "file": "枪械包/Sniper Ammo Box.glb",
    "bytes": 88404
  },
  {
    "id": "guns/sniper-rifle",
    "name": "Sniper Rifle",
    "category": "guns",
    "file": "枪械包/Sniper Rifle-ZkwSIy3JOV.glb",
    "bytes": 116892
  },
  {
    "id": "guns/sniper-rifle-2",
    "name": "Sniper Rifle",
    "category": "guns",
    "file": "枪械包/Sniper Rifle.glb",
    "bytes": 71640
  },
  {
    "id": "guns/submachine-gun",
    "name": "Submachine Gun",
    "category": "guns",
    "file": "枪械包/Submachine Gun-I9pqB6HWIC.glb",
    "bytes": 77768
  },
  {
    "id": "guns/submachine-gun-2",
    "name": "Submachine Gun",
    "category": "guns",
    "file": "枪械包/Submachine Gun-e66LWULNG4.glb",
    "bytes": 72788
  },
  {
    "id": "guns/submachine-gun-3",
    "name": "Submachine Gun",
    "category": "guns",
    "file": "枪械包/Submachine Gun-thBPAYTK5R.glb",
    "bytes": 40252
  },
  {
    "id": "guns/submachine-gun-4",
    "name": "Submachine Gun",
    "category": "guns",
    "file": "枪械包/Submachine Gun-wnFec6z9ii.glb",
    "bytes": 62912
  },
  {
    "id": "guns/submachine-gun-5",
    "name": "Submachine Gun",
    "category": "guns",
    "file": "枪械包/Submachine Gun.glb",
    "bytes": 55056
  },
  {
    "id": "survival/axe",
    "name": "Axe",
    "category": "survival",
    "file": "生存素材模型/Axe.glb",
    "bytes": 16196
  },
  {
    "id": "survival/backpack",
    "name": "Backpack",
    "category": "survival",
    "file": "生存素材模型/Backpack.glb",
    "bytes": 99444
  },
  {
    "id": "survival/battery",
    "name": "Battery",
    "category": "survival",
    "file": "生存素材模型/Battery-MYa3uWdwPU.glb",
    "bytes": 10764
  },
  {
    "id": "survival/battery-2",
    "name": "Battery",
    "category": "survival",
    "file": "生存素材模型/Battery.glb",
    "bytes": 9024
  },
  {
    "id": "survival/bear-trap",
    "name": "Bear Trap",
    "category": "survival",
    "file": "生存素材模型/Bear Trap.glb",
    "bytes": 35196
  },
  {
    "id": "survival/bonfire",
    "name": "Bonfire",
    "category": "survival",
    "file": "生存素材模型/Bonfire.glb",
    "bytes": 43676
  },
  {
    "id": "survival/can-broken",
    "name": "Can Broken",
    "category": "survival",
    "file": "生存素材模型/Can Broken.glb",
    "bytes": 25460
  },
  {
    "id": "survival/can-red",
    "name": "Can Red",
    "category": "survival",
    "file": "生存素材模型/Can Red.glb",
    "bytes": 21304
  },
  {
    "id": "survival/can",
    "name": "Can",
    "category": "survival",
    "file": "生存素材模型/Can.glb",
    "bytes": 25460
  },
  {
    "id": "survival/compass",
    "name": "Compass",
    "category": "survival",
    "file": "生存素材模型/Compass.glb",
    "bytes": 40552
  },
  {
    "id": "survival/first-aid-kit",
    "name": "First Aid Kit",
    "category": "survival",
    "file": "生存素材模型/First Aid Kit-wP00rePSRD.glb",
    "bytes": 44444
  },
  {
    "id": "survival/first-aid-kit-2",
    "name": "First Aid Kit",
    "category": "survival",
    "file": "生存素材模型/First Aid Kit.glb",
    "bytes": 18568
  },
  {
    "id": "survival/flare-gun",
    "name": "Flare Gun",
    "category": "survival",
    "file": "生存素材模型/Flare Gun.glb",
    "bytes": 31312
  },
  {
    "id": "survival/gas-can",
    "name": "Gas Can",
    "category": "survival",
    "file": "生存素材模型/Gas Can.glb",
    "bytes": 45724
  },
  {
    "id": "survival/knife",
    "name": "Knife",
    "category": "survival",
    "file": "生存素材模型/Knife.glb",
    "bytes": 28692
  },
  {
    "id": "survival/match-burnt",
    "name": "Match Burnt",
    "category": "survival",
    "file": "生存素材模型/Match Burnt.glb",
    "bytes": 5808
  },
  {
    "id": "survival/match",
    "name": "Match",
    "category": "survival",
    "file": "生存素材模型/Match.glb",
    "bytes": 4232
  },
  {
    "id": "survival/matchbox",
    "name": "Matchbox",
    "category": "survival",
    "file": "生存素材模型/Matchbox.glb",
    "bytes": 26220
  },
  {
    "id": "survival/pan",
    "name": "Pan",
    "category": "survival",
    "file": "生存素材模型/Pan.glb",
    "bytes": 16756
  },
  {
    "id": "survival/phone",
    "name": "Phone",
    "category": "survival",
    "file": "生存素材模型/Phone.glb",
    "bytes": 15180
  },
  {
    "id": "survival/pot",
    "name": "Pot",
    "category": "survival",
    "file": "生存素材模型/Pot-fyweVKYu0K.glb",
    "bytes": 19900
  },
  {
    "id": "survival/pot-2",
    "name": "Pot",
    "category": "survival",
    "file": "生存素材模型/Pot.glb",
    "bytes": 20072
  },
  {
    "id": "survival/propane-tank",
    "name": "Propane Tank",
    "category": "survival",
    "file": "生存素材模型/Propane Tank.glb",
    "bytes": 31956
  },
  {
    "id": "survival/radio",
    "name": "Radio",
    "category": "survival",
    "file": "生存素材模型/Radio.glb",
    "bytes": 28996
  },
  {
    "id": "survival/raft-paddle",
    "name": "Raft Paddle",
    "category": "survival",
    "file": "生存素材模型/Raft Paddle.glb",
    "bytes": 16792
  },
  {
    "id": "survival/raft",
    "name": "Raft",
    "category": "survival",
    "file": "生存素材模型/Raft.glb",
    "bytes": 58392
  },
  {
    "id": "survival/shovel",
    "name": "Shovel",
    "category": "survival",
    "file": "生存素材模型/Shovel.glb",
    "bytes": 32448
  },
  {
    "id": "survival/tent",
    "name": "Tent",
    "category": "survival",
    "file": "生存素材模型/Tent.glb",
    "bytes": 45036
  },
  {
    "id": "survival/torch",
    "name": "Torch",
    "category": "survival",
    "file": "生存素材模型/Torch.glb",
    "bytes": 37188
  },
  {
    "id": "survival/water-bottle",
    "name": "Water Bottle",
    "category": "survival",
    "file": "生存素材模型/Water Bottle.glb",
    "bytes": 18792
  },
  {
    "id": "survival/wood-log",
    "name": "Wood Log",
    "category": "survival",
    "file": "生存素材模型/Wood Log.glb",
    "bytes": 13904
  },
  {
    "id": "survival/wooden-torch",
    "name": "Wooden Torch",
    "category": "survival",
    "file": "生存素材模型/Wooden Torch.glb",
    "bytes": 27932
  },
  {
    "id": "natureClump/birch-trees",
    "name": "Birch Trees",
    "category": "natureClump",
    "file": "自然模型包/Birch Trees.glb",
    "bytes": 4194972
  },
  {
    "id": "natureClump/bushes",
    "name": "Bushes",
    "category": "natureClump",
    "file": "自然模型包/Bushes.glb",
    "bytes": 472900
  },
  {
    "id": "natureClump/dead-trees",
    "name": "Dead Trees",
    "category": "natureClump",
    "file": "自然模型包/Dead Trees-F5I0Q7TwO5.glb",
    "bytes": 2744172
  },
  {
    "id": "natureClump/dead-trees-2",
    "name": "Dead Trees",
    "category": "natureClump",
    "file": "自然模型包/Dead Trees.glb",
    "bytes": 2469436
  },
  {
    "id": "natureClump/flower-bushes",
    "name": "Flower Bushes",
    "category": "natureClump",
    "file": "自然模型包/Flower Bushes.glb",
    "bytes": 342312
  },
  {
    "id": "natureClump/flowers",
    "name": "Flowers",
    "category": "natureClump",
    "file": "自然模型包/Flowers.glb",
    "bytes": 372664
  },
  {
    "id": "natureClump/grass",
    "name": "Grass",
    "category": "natureClump",
    "file": "自然模型包/Grass.glb",
    "bytes": 767660
  },
  {
    "id": "natureClump/maple-trees",
    "name": "Maple Trees",
    "category": "natureClump",
    "file": "自然模型包/Maple Trees.glb",
    "bytes": 3355280
  },
  {
    "id": "natureClump/palm-trees",
    "name": "Palm Trees",
    "category": "natureClump",
    "file": "自然模型包/Palm Trees.glb",
    "bytes": 1120784
  },
  {
    "id": "natureClump/pine-trees",
    "name": "Pine Trees",
    "category": "natureClump",
    "file": "自然模型包/Pine Trees.glb",
    "bytes": 2675812
  },
  {
    "id": "natureClump/rocks",
    "name": "Rocks",
    "category": "natureClump",
    "file": "自然模型包/Rocks.glb",
    "bytes": 3152056
  },
  {
    "id": "natureClump/trees",
    "name": "Trees",
    "category": "natureClump",
    "file": "自然模型包/Trees.glb",
    "bytes": 3408276
  },
  {
    "id": "nature/bush-with-flowers",
    "name": "Bush with Flowers",
    "category": "nature",
    "file": "自然模型包大多/Bush with Flowers.glb",
    "bytes": 809728
  },
  {
    "id": "nature/bush",
    "name": "Bush",
    "category": "nature",
    "file": "自然模型包大多/Bush.glb",
    "bytes": 164712
  },
  {
    "id": "nature/clover",
    "name": "Clover",
    "category": "nature",
    "file": "自然模型包大多/Clover-u5SOgBFiut.glb",
    "bytes": 703820
  },
  {
    "id": "nature/clover-2",
    "name": "Clover",
    "category": "nature",
    "file": "自然模型包大多/Clover.glb",
    "bytes": 694432
  },
  {
    "id": "nature/dead-tree",
    "name": "Dead Tree",
    "category": "nature",
    "file": "自然模型包大多/Dead Tree-CD4edbPSGm.glb",
    "bytes": 2597644
  },
  {
    "id": "nature/dead-tree-2",
    "name": "Dead Tree",
    "category": "nature",
    "file": "自然模型包大多/Dead Tree-Mcd2zYqyww.glb",
    "bytes": 2623500
  },
  {
    "id": "nature/dead-tree-3",
    "name": "Dead Tree",
    "category": "nature",
    "file": "自然模型包大多/Dead Tree-MlmK5488ou.glb",
    "bytes": 2607636
  },
  {
    "id": "nature/dead-tree-4",
    "name": "Dead Tree",
    "category": "nature",
    "file": "自然模型包大多/Dead Tree-n8FhMgMldD.glb",
    "bytes": 2600420
  },
  {
    "id": "nature/dead-tree-5",
    "name": "Dead Tree",
    "category": "nature",
    "file": "自然模型包大多/Dead Tree.glb",
    "bytes": 2604428
  },
  {
    "id": "nature/fern",
    "name": "Fern",
    "category": "nature",
    "file": "自然模型包大多/Fern.glb",
    "bytes": 692724
  },
  {
    "id": "nature/flower-group",
    "name": "Flower Group",
    "category": "nature",
    "file": "自然模型包大多/Flower Group-LqTljN6Wg2.glb",
    "bytes": 1282616
  },
  {
    "id": "nature/flower-group-2",
    "name": "Flower Group",
    "category": "nature",
    "file": "自然模型包大多/Flower Group.glb",
    "bytes": 1242384
  },
  {
    "id": "nature/flower-petal",
    "name": "Flower Petal",
    "category": "nature",
    "file": "自然模型包大多/Flower Petal-LqvxG9OBOU.glb",
    "bytes": 531608
  },
  {
    "id": "nature/flower-petal-2",
    "name": "Flower Petal",
    "category": "nature",
    "file": "自然模型包大多/Flower Petal-eVE0j49ux9.glb",
    "bytes": 531684
  },
  {
    "id": "nature/flower-petal-3",
    "name": "Flower Petal",
    "category": "nature",
    "file": "自然模型包大多/Flower Petal-niuBUEJdvM.glb",
    "bytes": 532064
  },
  {
    "id": "nature/flower-petal-4",
    "name": "Flower Petal",
    "category": "nature",
    "file": "自然模型包大多/Flower Petal-tzG4JcqYWs.glb",
    "bytes": 531684
  },
  {
    "id": "nature/flower-petal-5",
    "name": "Flower Petal",
    "category": "nature",
    "file": "自然模型包大多/Flower Petal.glb",
    "bytes": 531668
  },
  {
    "id": "nature/flower-single",
    "name": "Flower Single",
    "category": "nature",
    "file": "自然模型包大多/Flower Single-GvfHo0roi3.glb",
    "bytes": 1237772
  },
  {
    "id": "nature/flower-single-2",
    "name": "Flower Single",
    "category": "nature",
    "file": "自然模型包大多/Flower Single.glb",
    "bytes": 1222572
  },
  {
    "id": "nature/grass-wispy",
    "name": "Grass Wispy",
    "category": "nature",
    "file": "自然模型包大多/Grass Wispy-Msr9zx66VU.glb",
    "bytes": 97188
  },
  {
    "id": "nature/grass-wispy-2",
    "name": "Grass Wispy",
    "category": "nature",
    "file": "自然模型包大多/Grass Wispy.glb",
    "bytes": 101412
  },
  {
    "id": "nature/grass",
    "name": "Grass",
    "category": "nature",
    "file": "自然模型包大多/Grass.glb",
    "bytes": 79796
  },
  {
    "id": "nature/mushroom-laetiporus",
    "name": "Mushroom Laetiporus",
    "category": "nature",
    "file": "自然模型包大多/Mushroom Laetiporus.glb",
    "bytes": 1262996
  },
  {
    "id": "nature/mushroom",
    "name": "Mushroom",
    "category": "nature",
    "file": "自然模型包大多/Mushroom.glb",
    "bytes": 1208932
  },
  {
    "id": "nature/pebble-round",
    "name": "Pebble Round",
    "category": "nature",
    "file": "自然模型包大多/Pebble Round-KYtJ6JNXh2.glb",
    "bytes": 813788
  },
  {
    "id": "nature/pebble-round-2",
    "name": "Pebble Round",
    "category": "nature",
    "file": "自然模型包大多/Pebble Round-icVsN3lmVy.glb",
    "bytes": 814208
  },
  {
    "id": "nature/pebble-round-3",
    "name": "Pebble Round",
    "category": "nature",
    "file": "自然模型包大多/Pebble Round-kAMfq1uJUY.glb",
    "bytes": 814628
  },
  {
    "id": "nature/pebble-round-4",
    "name": "Pebble Round",
    "category": "nature",
    "file": "自然模型包大多/Pebble Round-nMf8LHOsbM.glb",
    "bytes": 815064
  },
  {
    "id": "nature/pebble-round-5",
    "name": "Pebble Round",
    "category": "nature",
    "file": "自然模型包大多/Pebble Round.glb",
    "bytes": 813872
  },
  {
    "id": "nature/pebble-square",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square-2YtLzwgsWp.glb",
    "bytes": 813288
  },
  {
    "id": "nature/pebble-square-2",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square-6juX57sLHe.glb",
    "bytes": 816036
  },
  {
    "id": "nature/pebble-square-3",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square-Mm4RMgwNO8.glb",
    "bytes": 815108
  },
  {
    "id": "nature/pebble-square-4",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square-l5XiYQj1oD.glb",
    "bytes": 814232
  },
  {
    "id": "nature/pebble-square-5",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square-s71L3q1nXN.glb",
    "bytes": 814756
  },
  {
    "id": "nature/pebble-square-6",
    "name": "Pebble Square",
    "category": "nature",
    "file": "自然模型包大多/Pebble Square.glb",
    "bytes": 812940
  },
  {
    "id": "nature/pine",
    "name": "Pine",
    "category": "nature",
    "file": "自然模型包大多/Pine-699sFuLCN2.glb",
    "bytes": 2261060
  },
  {
    "id": "nature/pine-2",
    "name": "Pine",
    "category": "nature",
    "file": "自然模型包大多/Pine-79gmlLnweB.glb",
    "bytes": 2221932
  },
  {
    "id": "nature/pine-3",
    "name": "Pine",
    "category": "nature",
    "file": "自然模型包大多/Pine-Zt62gceKXZ.glb",
    "bytes": 2219996
  },
  {
    "id": "nature/pine-4",
    "name": "Pine",
    "category": "nature",
    "file": "自然模型包大多/Pine-rfnxJv0Rqa.glb",
    "bytes": 2228032
  },
  {
    "id": "nature/pine-5",
    "name": "Pine",
    "category": "nature",
    "file": "自然模型包大多/Pine.glb",
    "bytes": 2147312
  },
  {
    "id": "nature/plant-big",
    "name": "Plant Big",
    "category": "nature",
    "file": "自然模型包大多/Plant Big-MbhbP7JrTI.glb",
    "bytes": 698784
  },
  {
    "id": "nature/plant-big-2",
    "name": "Plant Big",
    "category": "nature",
    "file": "自然模型包大多/Plant Big.glb",
    "bytes": 683868
  },
  {
    "id": "nature/plant",
    "name": "Plant",
    "category": "nature",
    "file": "自然模型包大多/Plant-xH5gNlQxAZ.glb",
    "bytes": 681168
  },
  {
    "id": "nature/plant-2",
    "name": "Plant",
    "category": "nature",
    "file": "自然模型包大多/Plant.glb",
    "bytes": 685820
  },
  {
    "id": "nature/rock-medium",
    "name": "Rock Medium",
    "category": "nature",
    "file": "自然模型包大多/Rock Medium-JQxF95498B.glb",
    "bytes": 1071636
  },
  {
    "id": "nature/rock-medium-2",
    "name": "Rock Medium",
    "category": "nature",
    "file": "自然模型包大多/Rock Medium-s1OJ3bBzqc.glb",
    "bytes": 1064792
  },
  {
    "id": "nature/rock-medium-3",
    "name": "Rock Medium",
    "category": "nature",
    "file": "自然模型包大多/Rock Medium.glb",
    "bytes": 1060940
  },
  {
    "id": "nature/rock-path-round-small",
    "name": "Rock Path Round Small",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Round Small-GMttpOEFKT.glb",
    "bytes": 885132
  },
  {
    "id": "nature/rock-path-round-small-2",
    "name": "Rock Path Round Small",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Round Small-yHEdadj5I0.glb",
    "bytes": 876940
  },
  {
    "id": "nature/rock-path-round-small-3",
    "name": "Rock Path Round Small",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Round Small.glb",
    "bytes": 876836
  },
  {
    "id": "nature/rock-path-round-thin",
    "name": "Rock Path Round Thin",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Round Thin.glb",
    "bytes": 961044
  },
  {
    "id": "nature/rock-path-round-wide",
    "name": "Rock Path Round Wide",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Round Wide.glb",
    "bytes": 1044552
  },
  {
    "id": "nature/rock-path-square-smal",
    "name": "Rock Path Square Smal",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Square Smal-cI9XBpVijV.glb",
    "bytes": 862728
  },
  {
    "id": "nature/rock-path-square-smal-2",
    "name": "Rock Path Square Smal",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Square Smal-w4TKZMjjcw.glb",
    "bytes": 847876
  },
  {
    "id": "nature/rock-path-square-smal-3",
    "name": "Rock Path Square Smal",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Square Smal.glb",
    "bytes": 848472
  },
  {
    "id": "nature/rock-path-square-thin",
    "name": "Rock Path Square Thin",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Square Thin.glb",
    "bytes": 931564
  },
  {
    "id": "nature/rock-path-square-wide",
    "name": "Rock Path Square Wide",
    "category": "nature",
    "file": "自然模型包大多/Rock Path Square Wide.glb",
    "bytes": 963296
  },
  {
    "id": "nature/tall-grass",
    "name": "Tall Grass",
    "category": "nature",
    "file": "自然模型包大多/Tall Grass.glb",
    "bytes": 88020
  },
  {
    "id": "nature/tree",
    "name": "Tree",
    "category": "nature",
    "file": "自然模型包大多/Tree-QVOop92WmG.glb",
    "bytes": 2430844
  },
  {
    "id": "nature/tree-2",
    "name": "Tree",
    "category": "nature",
    "file": "自然模型包大多/Tree-aVOxaHRPWe.glb",
    "bytes": 2479888
  },
  {
    "id": "nature/tree-3",
    "name": "Tree",
    "category": "nature",
    "file": "自然模型包大多/Tree-qZtx0AHhcy.glb",
    "bytes": 2540428
  },
  {
    "id": "nature/tree-4",
    "name": "Tree",
    "category": "nature",
    "file": "自然模型包大多/Tree-t9KbsfYdXz.glb",
    "bytes": 2385268
  },
  {
    "id": "nature/tree-5",
    "name": "Tree",
    "category": "nature",
    "file": "自然模型包大多/Tree.glb",
    "bytes": 2385192
  },
  {
    "id": "nature/twisted-tree",
    "name": "Twisted Tree",
    "category": "nature",
    "file": "自然模型包大多/Twisted Tree-7PDBpElkQr.glb",
    "bytes": 3075984
  },
  {
    "id": "nature/twisted-tree-2",
    "name": "Twisted Tree",
    "category": "nature",
    "file": "自然模型包大多/Twisted Tree-8oraKn9m0x.glb",
    "bytes": 3089768
  },
  {
    "id": "nature/twisted-tree-3",
    "name": "Twisted Tree",
    "category": "nature",
    "file": "自然模型包大多/Twisted Tree-9aWlx82xUf.glb",
    "bytes": 3048260
  },
  {
    "id": "nature/twisted-tree-4",
    "name": "Twisted Tree",
    "category": "nature",
    "file": "自然模型包大多/Twisted Tree-GVTsMmuzv7.glb",
    "bytes": 3028976
  },
  {
    "id": "nature/twisted-tree-5",
    "name": "Twisted Tree",
    "category": "nature",
    "file": "自然模型包大多/Twisted Tree.glb",
    "bytes": 3119328
  },
  {
    "id": "food/apple-green",
    "name": "Apple Green",
    "category": "food",
    "file": "食物素材模型/Apple Green.glb",
    "bytes": 35740
  },
  {
    "id": "food/avocado",
    "name": "Avocado",
    "category": "food",
    "file": "食物素材模型/Avocado.glb",
    "bytes": 17612
  },
  {
    "id": "food/bacon",
    "name": "Bacon",
    "category": "food",
    "file": "食物素材模型/Bacon.glb",
    "bytes": 35412
  },
  {
    "id": "food/banana",
    "name": "Banana",
    "category": "food",
    "file": "食物素材模型/Banana.glb",
    "bytes": 20484
  },
  {
    "id": "food/bottle",
    "name": "Bottle",
    "category": "food",
    "file": "食物素材模型/Bottle-Pc8dM9Ja4V.glb",
    "bytes": 16328
  },
  {
    "id": "food/bottle-2",
    "name": "Bottle",
    "category": "food",
    "file": "食物素材模型/Bottle.glb",
    "bytes": 15376
  },
  {
    "id": "food/bread-slice",
    "name": "Bread Slice",
    "category": "food",
    "file": "食物素材模型/Bread Slice.glb",
    "bytes": 29136
  },
  {
    "id": "food/bread",
    "name": "Bread",
    "category": "food",
    "file": "食物素材模型/Bread.glb",
    "bytes": 29316
  },
  {
    "id": "food/broccoli",
    "name": "Broccoli",
    "category": "food",
    "file": "食物素材模型/Broccoli.glb",
    "bytes": 20688
  },
  {
    "id": "food/burger",
    "name": "Burger",
    "category": "food",
    "file": "食物素材模型/Burger.glb",
    "bytes": 57116
  },
  {
    "id": "food/carrot",
    "name": "Carrot",
    "category": "food",
    "file": "食物素材模型/Carrot.glb",
    "bytes": 49256
  },
  {
    "id": "food/cheeseburger",
    "name": "Cheeseburger",
    "category": "food",
    "file": "食物素材模型/Cheeseburger.glb",
    "bytes": 38416
  },
  {
    "id": "food/chicken-leg",
    "name": "Chicken Leg",
    "category": "food",
    "file": "食物素材模型/Chicken Leg.glb",
    "bytes": 18296
  },
  {
    "id": "food/chocolate-bar",
    "name": "Chocolate Bar",
    "category": "food",
    "file": "食物素材模型/Chocolate Bar.glb",
    "bytes": 24056
  },
  {
    "id": "food/chopsticks",
    "name": "Chopsticks",
    "category": "food",
    "file": "食物素材模型/Chopsticks.glb",
    "bytes": 25184
  },
  {
    "id": "food/cooking-pot",
    "name": "Cooking Pot",
    "category": "food",
    "file": "食物素材模型/Cooking Pot-lMEdEOMg9L.glb",
    "bytes": 14972
  },
  {
    "id": "food/cooking-pot-2",
    "name": "Cooking Pot",
    "category": "food",
    "file": "食物素材模型/Cooking Pot.glb",
    "bytes": 15016
  },
  {
    "id": "food/corndog",
    "name": "Corndog",
    "category": "food",
    "file": "食物素材模型/Corndog.glb",
    "bytes": 17884
  },
  {
    "id": "food/croissant",
    "name": "Croissant",
    "category": "food",
    "file": "食物素材模型/Croissant.glb",
    "bytes": 8248
  },
  {
    "id": "food/cupcake",
    "name": "Cupcake",
    "category": "food",
    "file": "食物素材模型/Cupcake.glb",
    "bytes": 27188
  },
  {
    "id": "food/donut",
    "name": "Donut",
    "category": "food",
    "file": "食物素材模型/Donut.glb",
    "bytes": 59172
  },
  {
    "id": "food/double-cheeseburger",
    "name": "Double Cheeseburger",
    "category": "food",
    "file": "食物素材模型/Double Cheeseburger.glb",
    "bytes": 53364
  },
  {
    "id": "food/egg-fried",
    "name": "Egg Fried",
    "category": "food",
    "file": "食物素材模型/Egg Fried.glb",
    "bytes": 7840
  },
  {
    "id": "food/egg",
    "name": "Egg",
    "category": "food",
    "file": "食物素材模型/Egg.glb",
    "bytes": 22040
  },
  {
    "id": "food/eggplant",
    "name": "Eggplant",
    "category": "food",
    "file": "食物素材模型/Eggplant.glb",
    "bytes": 22616
  },
  {
    "id": "food/fries",
    "name": "Fries",
    "category": "food",
    "file": "食物素材模型/Fries.glb",
    "bytes": 21272
  },
  {
    "id": "food/frying-pan",
    "name": "Frying Pan",
    "category": "food",
    "file": "食物素材模型/Frying Pan.glb",
    "bytes": 14064
  },
  {
    "id": "food/hotdog",
    "name": "Hotdog",
    "category": "food",
    "file": "食物素材模型/Hotdog.glb",
    "bytes": 58392
  },
  {
    "id": "food/ice-cream",
    "name": "Ice Cream",
    "category": "food",
    "file": "食物素材模型/Ice Cream.glb",
    "bytes": 74968
  },
  {
    "id": "food/ketchup-bottle",
    "name": "Ketchup Bottle",
    "category": "food",
    "file": "食物素材模型/Ketchup Bottle.glb",
    "bytes": 14060
  },
  {
    "id": "food/lettuce",
    "name": "Lettuce",
    "category": "food",
    "file": "食物素材模型/Lettuce.glb",
    "bytes": 33396
  },
  {
    "id": "food/mushroom-sliced",
    "name": "Mushroom Sliced",
    "category": "food",
    "file": "食物素材模型/Mushroom Sliced.glb",
    "bytes": 7424
  },
  {
    "id": "food/pancakes-stack",
    "name": "Pancakes Stack",
    "category": "food",
    "file": "食物素材模型/Pancakes Stack.glb",
    "bytes": 52496
  },
  {
    "id": "food/pepper-green",
    "name": "Pepper Green",
    "category": "food",
    "file": "食物素材模型/Pepper Green.glb",
    "bytes": 46584
  },
  {
    "id": "food/pizza-slice",
    "name": "Pizza Slice",
    "category": "food",
    "file": "食物素材模型/Pizza Slice.glb",
    "bytes": 23420
  },
  {
    "id": "food/pizza",
    "name": "Pizza",
    "category": "food",
    "file": "食物素材模型/Pizza.glb",
    "bytes": 61164
  },
  {
    "id": "food/plate-square",
    "name": "Plate Square",
    "category": "food",
    "file": "食物素材模型/Plate Square.glb",
    "bytes": 11856
  },
  {
    "id": "food/popsicle-chocolate",
    "name": "Popsicle Chocolate",
    "category": "food",
    "file": "食物素材模型/Popsicle Chocolate.glb",
    "bytes": 7052
  },
  {
    "id": "food/popsicle",
    "name": "Popsicle",
    "category": "food",
    "file": "食物素材模型/Popsicle.glb",
    "bytes": 11076
  },
  {
    "id": "food/pumpkin",
    "name": "Pumpkin",
    "category": "food",
    "file": "食物素材模型/Pumpkin.glb",
    "bytes": 37424
  },
  {
    "id": "food/soda",
    "name": "Soda",
    "category": "food",
    "file": "食物素材模型/Soda.glb",
    "bytes": 27684
  },
  {
    "id": "food/spoon",
    "name": "Spoon",
    "category": "food",
    "file": "食物素材模型/Spoon.glb",
    "bytes": 10372
  },
  {
    "id": "food/steak",
    "name": "Steak",
    "category": "food",
    "file": "食物素材模型/Steak.glb",
    "bytes": 25312
  },
  {
    "id": "food/sushi-nigiri",
    "name": "Sushi Nigiri",
    "category": "food",
    "file": "食物素材模型/Sushi Nigiri.glb",
    "bytes": 13236
  },
  {
    "id": "food/sushi",
    "name": "Sushi",
    "category": "food",
    "file": "食物素材模型/Sushi.glb",
    "bytes": 12208
  },
  {
    "id": "food/tentacle",
    "name": "Tentacle",
    "category": "food",
    "file": "食物素材模型/Tentacle.glb",
    "bytes": 35084
  },
  {
    "id": "food/tomato-slice",
    "name": "Tomato Slice",
    "category": "food",
    "file": "食物素材模型/Tomato Slice.glb",
    "bytes": 35964
  },
  {
    "id": "food/tomato",
    "name": "Tomato",
    "category": "food",
    "file": "食物素材模型/Tomato.glb",
    "bytes": 27128
  },
  {
    "id": "food/turnip",
    "name": "Turnip",
    "category": "food",
    "file": "食物素材模型/Turnip.glb",
    "bytes": 56388
  },
  {
    "id": "food/waffle",
    "name": "Waffle",
    "category": "food",
    "file": "食物素材模型/Waffle.glb",
    "bytes": 59472
  }
]

export function assetById(id: string): AssetEntry | undefined {
  return ASSET_INDEX.find((entry) => entry.id === id)
}

export function assetsIn(category: AssetCategory): AssetEntry[] {
  return ASSET_INDEX.filter((entry) => entry.category === category)
}

export function assetUrl(file: string): string {
  return `/assets/${file.split('/').map(encodeURIComponent).join('/')}`
}
